[package]
name = "minerva-report-uiuc"
version = "0.1.0"
entrypoint = "minerva-report-uiuc.typ"
authors = ["Raúl de la Fuente <@lomolisso>", "David Ibáñez <@Dav1com>"]
repository = "https://github.com/lomolisso/minerva-report-uiuc"
license = "MIT-0"
description = "Professional template for assignments, reports, and academic papers for the University of Illinois at Urbana-Champaign."
keywords = ["uiuc", "University of Illinois", "engineering", "assignment", "homework", "report", "academic", "en", "english"]
categories = ["report"]
compiler = "0.13.0"
exclude = ["guide.pdf"]

[template]
path = "template"
entrypoint = "main.typ"